name: cep_project
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Local storage
  shared_preferences: ^2.0.15

  #Client http
  dio: ^4.0.6

  #UX/UI
  lottie: ^1.3.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.2

  #State management
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11



flutter:
  uses-material-design: true
  assets:
    - assets/images/

  